services:
  - type: web
    name: betsoka
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: NODE_VERSION
        value: "20.11.1"
